export default {
  "OBJECTID": "Object ID",
  "NAME": "Name",
  "STATE_NAME": "State",
  "STATE_ABBR": "Abbreviation",
  "STATE_FIPS": "State FIPS Code",
  "COUNTY_FIPS": "County FIPS Code",
  "GEOID": "Geographic Identifier - FIPS Code",
  "POPULATION": "2022 Population",
  "ALMDS_ACRES_BEARING_NON_BEARING": "Almonds - Acres Bearing & Non-Bearing",
  "ALMDS_ACRES_BEARING": "Almonds - Acres Bearing",
  "ALMDS_ACRES_NON_BEARING": "Almonds - Acres Non-Bearing",
  "ALMDS_OPS_W_AREA_BEAR_NONBEAR": "Almonds - Operations With Area Bearing & Non-Bearing",
  "ALMDS_OPS_W_AREA_BEARING": "Almonds - Operations With Area Bearing",
  "ALMDS_OPS_W_AREA_NON_BEARING": "Almonds - Operations With Area Non-Bearing",
  "ANIMAL_TOT_EXP_DOLS": "Animal Totals - Expense, Measured In US Dollars ($)",
  "ANIMAL_TOT_OPS_W_EXP": "Animal Totals - Operations With Expense",
  "ANIMAL_TOT_EXCL_BREED_EXP_DOL": "Animal Totals, (Excl Breeding) - Expense, Measured In US Dollars ($)",
  "ANIMAL_TOT_EXCL_BREED_OPS_W_EXP": "Animal Totals, (Excl Breeding) - Operations With Expense",
  "ANIMAL_TOT_BREED_EXP_DOL": "Animal Totals, Breeding - Expense, Measured In US Dollars ($)",
  "ANIMAL_TOT_BREED_OPS_W_EXP": "Animal Totals, Breeding - Operations With Expense",
  "ANIMAL_TOT_IN_PROD_OPS_W_SALES": "Animal Totals, Incl Products - Operations With Sales",
  "ANIMAL_TOT_IN_PROD_SALES_DOL": "Animal Totals, Incl Products - Sales, Measured In US Dollars ($)",
  "BARLEY_AC_HRVST": "Barley - Acres Harvested",
  "BARLEY_OPS_A_HRVST_1K_PLS_AC": "Barley - Operations With Area Harvested - Area Harvested: (1,000 Or More Acres)",
  "BARLEY_OPS_A_HRVST_1_25_AC": "Barley - Operations With Area Harvested - Area Harvested: (1.0 To 24.9 Acres)",
  "BARLEY_OPS_A_HRVST_100_249_AC": "Barley - Operations With Area Harvested - Area Harvested: (100 To 249 Acres)",
  "BARLEY_OPS_A_HRVST_25_100_AC": "Barley - Operations With Area Harvested - Area Harvested: (25.0 To 99.9 Acres)",
  "BARLEY_OPS_A_HRVST_250_500_AC": "Barley - Operations With Area Harvested - Area Harvested: (250 To 499 Acres)",
  "BARLEY_OPS_A_HRVST_500_999_AC": "Barley - Operations With Area Harvested - Area Harvested: (500 To 999 Acres)",
  "BARLEY_OPS_A_HRVST": "Barley - Operations With Area Harvested",
  "BARLEY_OPS_SALES": "Barley - Operations With Sales",
  "BARLEY_PROD_IN_BU": "Barley - Production, Measured In Bushels",
  "BARLEY_SALES_IN_DOL": "Barley - Sales, Measured In US Dollars ($)",
  "BARLEY_IRRIGATED_ACRES_HRVST": "Barley, Irrigated - Acres Harvested",
  "BARLEY_IRRIGATED_OPS_AREA_HRVST": "Barley, Irrigated - Operations With Area Harvested",
  "CATTLE_EXCL_COWS_INV_1_9": "Cattle, (Excl Cows) - Inventory - Inventory Of Cattle, (Excl Cows): (1 To 9 Head)",
  "CATTLE_EXCL_COWS_INV_10_19": "Cattle, (Excl Cows) - Inventory - Inventory Of Cattle, (Excl Cows): (10 To 19 Head)",
  "CATTLE_EXCL_COWS_INV_100_199": "Cattle, (Excl Cows) - Inventory - Inventory Of Cattle, (Excl Cows): (100 To 199 Head)",
  "CATTLE_EXCL_COWS_INV_20_49": "Cattle, (Excl Cows) - Inventory - Inventory Of Cattle, (Excl Cows): (20 To 49 Head)",
  "CATTLE_EXCL_COWS_INV_200_299": "Cattle, (Excl Cows) - Inventory - Inventory Of Cattle, (Excl Cows): (200 To 499 Head)",
  "CATTLE_EXCL_COWS_INV_50_99": "Cattle, (Excl Cows) - Inventory - Inventory Of Cattle, (Excl Cows): (50 To 99 Head)",
  "CATTLE_EXCL_COWS_INV_500_PLS": "Cattle, (Excl Cows) - Inventory - Inventory Of Cattle, (Excl Cows): (500 Or More Head)",
  "CATTLE_EXCL_COWS_INV": "Cattle, (Excl Cows) - Inventory",
  "CATTLE_EXCL_COWS_OPS_1_9": "Cattle, (Excl Cows) - Operations With Inventory - Inventory Of Cattle, (Excl Cows): (1 To 9 Head)",
  "CATTLE_EXCL_COWS_OPS_10_19": "Cattle, (Excl Cows) - Operations With Inventory - Inventory Of Cattle, (Excl Cows): (10 To 19 Head)",
  "CATTLE_EXCL_COWS_OPS__100_199": "Cattle, (Excl Cows) - Operations With Inventory - Inventory Of Cattle, (Excl Cows): (100 To 199 Head)",
  "CATTLE_EXCL_COWS_OPS_29_49": "Cattle, (Excl Cows) - Operations With Inventory - Inventory Of Cattle, (Excl Cows): (20 To 49 Head)",
  "CATTLE_EXCL_COWS_OPS_200_499": "Cattle, (Excl Cows) - Operations With Inventory - Inventory Of Cattle, (Excl Cows): (200 To 499 Head)",
  "CATTLE_EXCL_COWS_OPS_50_99": "Cattle, (Excl Cows) - Operations With Inventory - Inventory Of Cattle, (Excl Cows): (50 To 99 Head)",
  "CATTLE_EXCL_COWS_OPS_500_PLS": "Cattle, (Excl Cows) - Operations With Inventory - Inventory Of Cattle, (Excl Cows): (500 Or More Head)",
  "CATTLE_EXCL_COWS_OPS_INV": "Cattle, (Excl Cows) - Operations With Inventory",
  "CATTLE_CALVES_OPS_SALES_1_9": "Cattle, Calves - Operations With Sales - Sales Of Calves: (1 To 9 Head)",
  "CATTLE_CALVES_OPS_SALES_10_19": "Cattle, Calves - Operations With Sales - Sales Of Calves: (10 To 19 Head)",
  "CATTLE_CALVES_OPS_SALES_100_199": "Cattle, Calves - Operations With Sales - Sales Of Calves: (100 To 199 Head)",
  "CATTLE_CALVES_OPS_SALES_20_49": "Cattle, Calves - Operations With Sales - Sales Of Calves: (20 To 49 Head)",
  "CATTLE_CALVES_OPS_SALES_200_499": "Cattle, Calves - Operations With Sales - Sales Of Calves: (200 To 499 Head)",
  "CATTLE_CALVES_OPS_SALES_50_99": "Cattle, Calves - Operations With Sales - Sales Of Calves: (50 To 99 Head)",
  "CATTLE_CALVES_OPS_SALES_500_PLS": "Cattle, Calves - Operations With Sales - Sales Of Calves: (500 Or More Head)",
  "CATTLE_CALVES_OPS_SALES": "Cattle, Calves - Operations With Sales",
  "CATTLE_CALVES_SALES_H_1_9": "Cattle, Calves - Sales, Measured In Head - Sales Of Calves: (1 To 9 Head)",
  "CATTLE_CALVES_SALES_H_10_19": "Cattle, Calves - Sales, Measured In Head - Sales Of Calves: (10 To 19 Head)",
  "CATTLE_CALVES_SALES_H_100_199": "Cattle, Calves - Sales, Measured In Head - Sales Of Calves: (100 To 199 Head)",
  "CATTLE_CALVES_SALES_H_20_49": "Cattle, Calves - Sales, Measured In Head - Sales Of Calves: (20 To 49 Head)",
  "CATTLE_CALVES_SALES_H_200_499": "Cattle, Calves - Sales, Measured In Head - Sales Of Calves: (200 To 499 Head)",
  "CATTLE_CALVES_SALES_H_50_99": "Cattle, Calves - Sales, Measured In Head - Sales Of Calves: (50 To 99 Head)",
  "CATTLE_CALVES_SALES_H_500_PLS": "Cattle, Calves - Sales, Measured In Head - Sales Of Calves: (500 Or More Head)",
  "CATTLE_CALVES_SALES_IN_H_TOT": "Cattle, Calves - Sales, Measured In Head",
  "CATTLE_CALVES_VEAL_RSD_SOLD_OP": "Cattle, Calves, Veal, Raised Or Sold - Number Of Operations",
  "CATTLE_COWS_INV": "Cattle, Cows - Inventory",
  "CATTLE_COWS_OPS_INV": "Cattle, Cows - Operations With Inventory",
  "CATTLE_COWS_BEEF_INV_1_9": "Cattle, Cows, Beef - Inventory - Inventory Of Beef Cows: (1 To 9 Head)",
  "CATTLE_COWS_BEEF_INV_10_19": "Cattle, Cows, Beef - Inventory - Inventory Of Beef Cows: (10 To 19 Head)",
  "CATTLE_COWS_BEEF_INV_100_199": "Cattle, Cows, Beef - Inventory - Inventory Of Beef Cows: (100 To 199 Head)",
  "CATTLE_COWS_BEEF_INV_20_49": "Cattle, Cows, Beef - Inventory - Inventory Of Beef Cows: (20 To 49 Head)",
  "CATTLE_COWS_BEEF_INV_200_499": "Cattle, Cows, Beef - Inventory - Inventory Of Beef Cows: (200 To 499 Head)",
  "CATTLE_COWS_BEEF_INV_50_99": "Cattle, Cows, Beef - Inventory - Inventory Of Beef Cows: (50 To 99 Head)",
  "CATTLE_COWS_BEEF_INV_500_PLS": "Cattle, Cows, Beef - Inventory - Inventory Of Beef Cows: (500 Or More Head)",
  "CATTLE_COWS_BEEF_INV": "Cattle, Cows, Beef - Inventory",
  "CATTLE_COWS_BEEF_OPS_INV_1_9": "Cattle, Cows, Beef - Operations With Inventory - Inventory Of Beef Cows: (1 To 9 Head)",
  "CATTLE_COWS_BEEF_OPS_INV_10_19": "Cattle, Cows, Beef - Operations With Inventory - Inventory Of Beef Cows: (10 To 19 Head)",
  "CATTLE_COWS_BEEF_OPS_INV100_199": "Cattle, Cows, Beef - Operations With Inventory - Inventory Of Beef Cows: (100 To 199 Head)",
  "CATTLE_COWS_BEEF_OPS_INV_20_49": "Cattle, Cows, Beef - Operations With Inventory - Inventory Of Beef Cows: (20 To 49 Head)",
  "CATTLE_COWS_BEEF_OPS_INV200_499": "Cattle, Cows, Beef - Operations With Inventory - Inventory Of Beef Cows: (200 To 499 Head)",
  "CATTLE_COWS_BEEF_OPS_INV_50_99": "Cattle, Cows, Beef - Operations With Inventory - Inventory Of Beef Cows: (50 To 99 Head)",
  "CATTLE_COWS_BEEF_OPS_INV500_PLS": "Cattle, Cows, Beef - Operations With Inventory - Inventory Of Beef Cows: (500 Or More Head)",
  "CATTLE_COWS_BEEF_OPS_INV": "Cattle, Cows, Beef - Operations With Inventory",
  "CATTLE_COWS_MILK_INV_1_9": "Cattle, Cows, Milk - Inventory - Inventory Of Milk Cows: (1 To 9 Head)",
  "CATTLE_COWS_MILK_INV_10_19": "Cattle, Cows, Milk - Inventory - Inventory Of Milk Cows: (10 To 19 Head)",
  "CATTLE_COWS_MILK_INV_100_199": "Cattle, Cows, Milk - Inventory - Inventory Of Milk Cows: (100 To 199 Head)",
  "CATTLE_COWS_MILK_INV_20_49": "Cattle, Cows, Milk - Inventory - Inventory Of Milk Cows: (20 To 49 Head)",
  "CATTLE_COWS_MILK_INV_200_499": "Cattle, Cows, Milk - Inventory - Inventory Of Milk Cows: (200 To 499 Head)",
  "CATTLE_COWS_MILK_INV_50_99": "Cattle, Cows, Milk - Inventory - Inventory Of Milk Cows: (50 To 99 Head)",
  "CATTLE_COWS_MILK_INV_500_PLS": "Cattle, Cows, Milk - Inventory - Inventory Of Milk Cows: (500 Or More Head)",
  "CATTLE_COWS_MILK_INV": "Cattle, Cows, Milk - Inventory",
  "CATTLE_COWS_MILK_OPS_INV_1_9": "Cattle, Cows, Milk - Operations With Inventory - Inventory Of Milk Cows: (1 To 9 Head)",
  "CATTLE_COWS_MILK_OPS_INV_10_19": "Cattle, Cows, Milk - Operations With Inventory - Inventory Of Milk Cows: (10 To 19 Head)",
  "CATTLE_COWS_MILK_OPS_INV100_199": "Cattle, Cows, Milk - Operations With Inventory - Inventory Of Milk Cows: (100 To 199 Head)",
  "CATTLE_COWS_MILK_OPS_INV_20_49": "Cattle, Cows, Milk - Operations With Inventory - Inventory Of Milk Cows: (20 To 49 Head)",
  "CATTLE_COWS_MILK_OPS_INV200_499": "Cattle, Cows, Milk - Operations With Inventory - Inventory Of Milk Cows: (200 To 499 Head)",
  "CATTLE_COWS_MILK_OPS_INV_50_99": "Cattle, Cows, Milk - Operations With Inventory - Inventory Of Milk Cows: (50 To 99 Head)",
  "CATTLE_COWS_MILK_OPS_INV500_PLS": "Cattle, Cows, Milk - Operations With Inventory - Inventory Of Milk Cows: (500 Or More Head)",
  "CATTLE_COWS_MILK_OPS_INV": "Cattle, Cows, Milk - Operations With Inventory",
  "CATTLE_GE500_P_OPS_SALES_1_9": "Cattle, >= 500 Lbs - Operations With Sales - Sales Of Cattle >= 500 Lbs: (1 To 9 Head)",
  "CATTLE_GE500_P_OPS_SALES_10_19": "Cattle, >= 500 Lbs - Operations With Sales - Sales Of Cattle >= 500 Lbs: (10 To 19 Head)",
  "CATTLE_GE500_P_OPS_SALES100_199": "Cattle, >= 500 Lbs - Operations With Sales - Sales Of Cattle >= 500 Lbs: (100 To 199 Head)",
  "CATTLE_GE500_P_OPS_SALES_20_49": "Cattle, >= 500 Lbs - Operations With Sales - Sales Of Cattle >= 500 Lbs: (20 To 49 Head)",
  "CATTLE_GE500_P_OPS_SALES200_499": "Cattle, >= 500 Lbs - Operations With Sales - Sales Of Cattle >= 500 Lbs: (200 To 499 Head)",
  "CATTLE_GE500_P_OPS_SALES_50_99": "Cattle, >= 500 Lbs - Operations With Sales - Sales Of Cattle >= 500 Lbs: (50 To 99 Head)",
  "CATTLE_GE500_P_OPS_SALES500_PLS": "Cattle, >= 500 Lbs - Operations With Sales - Sales Of Cattle >= 500 Lbs: (500 Or More Head)",
  "CATTLE_GE500_P_OPS_SALES": "Cattle, >= 500 Lbs - Operations With Sales",
  "CATTLE_GE500_P_SALES_H_1_9": "Cattle, >= 500 Lbs - Sales, Measured In Head - Sales Of Cattle >= 500 Lbs: (1 To 9 Head)",
  "CATTLE_GE500_P_SALES_H_10_19": "Cattle, >= 500 Lbs - Sales, Measured In Head - Sales Of Cattle >= 500 Lbs: (10 To 19 Head)",
  "CATTLE_GE500_P_SALES_H_100_199": "Cattle, >= 500 Lbs - Sales, Measured In Head - Sales Of Cattle >= 500 Lbs: (100 To 199 Head)",
  "CATTLE_GE500_P_SALES_H_20_49": "Cattle, >= 500 Lbs - Sales, Measured In Head - Sales Of Cattle >= 500 Lbs: (20 To 49 Head)",
  "CATTLE_GE500_P_SALES_H_200_499": "Cattle, >= 500 Lbs - Sales, Measured In Head - Sales Of Cattle >= 500 Lbs: (200 To 499 Head)",
  "CATTLE_GE500_P_SALES_H_50_99": "Cattle, >= 500 Lbs - Sales, Measured In Head - Sales Of Cattle >= 500 Lbs: (50 To 99 Head)",
  "CATTLE_GE500_P_SALES_H_500_PLS": "Cattle, >= 500 Lbs - Sales, Measured In Head - Sales Of Cattle >= 500 Lbs: (500 Or More Head)",
  "CATTLE_GE500_P_SALES_IN_H_TOT": "Cattle, >= 500 Lbs - Sales, Measured In Head",
  "CATTLE_HFRS_GE500_RPLT_OPS": "Cattle, Heifers, >= 500 Lbs, Milk Replacement, Production Contract - Operations With Production",
  "CATTLE_HFRS_GE500_P_RPLT_H": "Cattle, Heifers, >= 500 Lbs, Milk Replacement, Production Contract - Production, Measured In Head",
  "CATTLE_INCL_CLVS_INV_1_9": "Cattle, Incl Calves - Inventory - Inventory Of Cattle, Incl Calves: (1 To 9 Head)",
  "CATTLE_INCL_CLVS_INV_10_19": "Cattle, Incl Calves - Inventory - Inventory Of Cattle, Incl Calves: (10 To 19 Head)",
  "CATTLE_INCL_CLVS_INV_100_199": "Cattle, Incl Calves - Inventory - Inventory Of Cattle, Incl Calves: (100 To 199 Head)",
  "CATTLE_INCL_CLVS_INV_20_49": "Cattle, Incl Calves - Inventory - Inventory Of Cattle, Incl Calves: (20 To 49 Head)",
  "CATTLE_INCL_CLVS_INV_200_499": "Cattle, Incl Calves - Inventory - Inventory Of Cattle, Incl Calves: (200 To 499 Head)",
  "CATTLE_INCL_CLVS_INV_50_99": "Cattle, Incl Calves - Inventory - Inventory Of Cattle, Incl Calves: (50 To 99 Head)",
  "CATTLE_INCL_CLVS_INV_500_PLS": "Cattle, Incl Calves - Inventory - Inventory Of Cattle, Incl Calves: (500 Or More Head)",
  "CATTLE_INCL_CLVS_INV": "Cattle, Incl Calves - Inventory",
  "CATTLE_INCL_CLVS_OPS_INV_1_9": "Cattle, Incl Calves - Operations With Inventory - Inventory Of Cattle, Incl Calves: (1 To 9 Head)",
  "CATTLE_INCL_CLVS_OPS_INV_10_19": "Cattle, Incl Calves - Operations With Inventory - Inventory Of Cattle, Incl Calves: (10 To 19 Head)",
  "CATTLE_INCL_CLVS_OPS_INV_100199": "Cattle, Incl Calves - Operations With Inventory - Inventory Of Cattle, Incl Calves: (100 To 199 Head)",
  "CATTLE_INCL_CLVS_OPS_INV_20_49": "Cattle, Incl Calves - Operations With Inventory - Inventory Of Cattle, Incl Calves: (20 To 49 Head)",
  "CATTLE_INCL_CLVS_OPS_INV_200499": "Cattle, Incl Calves - Operations With Inventory - Inventory Of Cattle, Incl Calves: (200 To 499 Head)",
  "CATTLE_INCL_CLVS_OPS_INV_50_99": "Cattle, Incl Calves - Operations With Inventory - Inventory Of Cattle, Incl Calves: (50 To 99 Head)",
  "CATTLE_INCL_CLVS_OPS_INV_500PLS": "Cattle, Incl Calves - Operations With Inventory - Inventory Of Cattle, Incl Calves: (500 Or More Head)",
  "CATTLE_INCL_CLVS_OPS_INV": "Cattle, Incl Calves - Operations With Inventory",
  "CATTLE_SALS_INCL_CLVS_1_9": "Cattle, Incl Calves - Operations With Sales - Sales Of Cattle, Incl Calves: (1 To 9 Head)",
  "CATTLE_SALS_INCL_CLVS_10_19": "Cattle, Incl Calves - Operations With Sales - Sales Of Cattle, Incl Calves: (10 To 19 Head)",
  "CATTLE_SALS_INCL_CLVS_100_199": "Cattle, Incl Calves - Operations With Sales - Sales Of Cattle, Incl Calves: (100 To 199 Head)",
  "CATTLE_SALS_INCL_CLVS_20_49": "Cattle, Incl Calves - Operations With Sales - Sales Of Cattle, Incl Calves: (20 To 49 Head)",
  "CATTLE_SALS_INCL_CLVS_200_499": "Cattle, Incl Calves - Operations With Sales - Sales Of Cattle, Incl Calves: (200 To 499 Head)",
  "CATTLE_SALS_INCL_CLVS_50_99": "Cattle, Incl Calves - Operations With Sales - Sales Of Cattle, Incl Calves: (50 To 99 Head)",
  "CATTLE_SALS_INCL_CLVS_500_PLS": "Cattle, Incl Calves - Operations With Sales - Sales Of Cattle, Incl Calves: (500 Or More Head)",
  "CATTLE_OPS_SALES_INCL_CLVS": "Cattle, Incl Calves - Operations With Sales",
  "CATTLE_SALS_INCL_CLVS_DOL": "Cattle, Incl Calves - Sales, Measured In US Dollars ($)",
  "CATTLE_SALS_INCL_CLVS_H_1_9": "Cattle, Incl Calves - Sales, Measured In Head - Sales Of Cattle, Incl Calves: (1 To 9 Head)",
  "CATTLE_SALS_INCL_CLVS_H_10_19": "Cattle, Incl Calves - Sales, Measured In Head - Sales Of Cattle, Incl Calves: (10 To 19 Head)",
  "CATTLE_SALS_INCL_CLVS_H_100_199": "Cattle, Incl Calves - Sales, Measured In Head - Sales Of Cattle, Incl Calves: (100 To 199 Head)",
  "CATTLE_SALS_INCL_CLVS_H_20_49": "Cattle, Incl Calves - Sales, Measured In Head - Sales Of Cattle, Incl Calves: (20 To 49 Head)",
  "CATTLE_SALS_INCL_CLVS_H_200_499": "Cattle, Incl Calves - Sales, Measured In Head - Sales Of Cattle, Incl Calves: (200 To 499 Head)",
  "CATTLE_SALS_INCL_CLVS_H_50_99": "Cattle, Incl Calves - Sales, Measured In Head - Sales Of Cattle, Incl Calves: (50 To 99 Head)",
  "CATTLE_SALS_INCL_CLVS_H_500_PLS": "Cattle, Incl Calves - Sales, Measured In Head - Sales Of Cattle, Incl Calves: (500 Or More Head)",
  "CATTLE_SALS_INCL_CLVS_H_TOT": "Cattle, Incl Calves - Sales, Measured In Head",
  "CATTLE_INV_ON_FEED_1_19": "Cattle, On Feed - Inventory - Inventory Of Cattle On Feed: (1 To 19 Head)",
  "CATTLE_INV_ON_FEED_100_199": "Cattle, On Feed - Inventory - Inventory Of Cattle On Feed: (100 To 199 Head)",
  "CATTLE_INV_ON_FEED_20_49": "Cattle, On Feed - Inventory - Inventory Of Cattle On Feed: (20 To 49 Head)",
  "CATTLE_INV_ON_FEED_200_499": "Cattle, On Feed - Inventory - Inventory Of Cattle On Feed: (200 To 499 Head)",
  "CATTLE_INV_ON_FEED_50_99": "Cattle, On Feed - Inventory - Inventory Of Cattle On Feed: (50 To 99 Head)",
  "CATTLE_INV_ON_FEED_500_PLS": "Cattle, On Feed - Inventory - Inventory Of Cattle On Feed: (500 Or More Head)",
  "CATTLE_INV_ON_FEED": "Cattle, On Feed - Inventory",
  "CATTLE_OPS_INV_ON_FEED_1_9": "Cattle, On Feed - Operations With Inventory - Inventory Of Cattle On Feed: (1 To 19 Head)",
  "CATTLE_OPS_INV_ON_FEED_100_199": "Cattle, On Feed - Operations With Inventory - Inventory Of Cattle On Feed: (100 To 199 Head)",
  "CATTLE_OPS_INV_ON_FEED_20_49": "Cattle, On Feed - Operations With Inventory - Inventory Of Cattle On Feed: (20 To 49 Head)",
  "CATTLE_OPS_INV_ON_FEED_200_499": "Cattle, On Feed - Operations With Inventory - Inventory Of Cattle On Feed: (200 To 499 Head)",
  "CATTLE_OPS_INV_ON_FEED_50_99": "Cattle, On Feed - Operations With Inventory - Inventory Of Cattle On Feed: (50 To 99 Head)",
  "CATTLE_OPS_INV_ON_FEED_500_PLS": "Cattle, On Feed - Operations With Inventory - Inventory Of Cattle On Feed: (500 Or More Head)",
  "CATTLE_OPS_INV_ON_FEED": "Cattle, On Feed - Operations With Inventory",
  "CATTLE_OPS_SLTR_ON_FEED_1_19": "Cattle, On Feed - Operations With Sales For Slaughter - Sales Of Cattle On Feed: (1 To 19 Head)",
  "CATTLE_OPS_SLTR_ON_FEED_100_199": "Cattle, On Feed - Operations With Sales For Slaughter - Sales Of Cattle On Feed: (100 To 199 Head)",
  "CATTLE_OPS_SLTR_ON_FEED_20_49": "Cattle, On Feed - Operations With Sales For Slaughter - Sales Of Cattle On Feed: (20 To 49 Head)",
  "CATTLE_OPS_SLTR_ON_FEED_200_499": "Cattle, On Feed - Operations With Sales For Slaughter - Sales Of Cattle On Feed: (200 To 499 Head)",
  "CATTLE_OPS_SLTR_ON_FEED_50_99": "Cattle, On Feed - Operations With Sales For Slaughter - Sales Of Cattle On Feed: (50 To 99 Head)",
  "CATTLE_OPS_SLTR_ON_FEED_500_PLS": "Cattle, On Feed - Operations With Sales For Slaughter - Sales Of Cattle On Feed: (500 Or More Head)",
  "CATTLE_OPS_SLTR_ON_FEED": "Cattle, On Feed - Operations With Sales For Slaughter",
  "CATTLE_SALES_SLTR_IN_H_1_9": "Cattle, On Feed - Sales For Slaughter, Measured In Head - Sales Of Cattle On Feed: (1 To 19 Head)",
  "CATTLE_SALES_SLTR_IN_H_100_199": "Cattle, On Feed - Sales For Slaughter, Measured In Head - Sales Of Cattle On Feed: (100 To 199 Head)",
  "CATTLE_SALES_SLTR_IN_H_20_49": "Cattle, On Feed - Sales For Slaughter, Measured In Head - Sales Of Cattle On Feed: (20 To 49 Head)",
  "CATTLE_SALES_SLTR_IN_H_200_499": "Cattle, On Feed - Sales For Slaughter, Measured In Head - Sales Of Cattle On Feed: (200 To 499 Head)",
  "CATTLE_SALES_SLTR_IN_H_50_99": "Cattle, On Feed - Sales For Slaughter, Measured In Head - Sales Of Cattle On Feed: (50 To 99 Head)",
  "CATTLE_SALES_SLTR_IN_H_500_PLS": "Cattle, On Feed - Sales For Slaughter, Measured In Head - Sales Of Cattle On Feed: (500 Or More Head)",
  "CATTLE_SALES_SLTR_IN_H_TOT": "Cattle, On Feed - Sales For Slaughter, Measured In Head",
  "CATTLE_PROD_CON_OPS_PROD": "Cattle, Production Contract, On Feed - Operations With Production",
  "CATTLE_PROD_CON_PROD_IN_H": "Cattle, Production Contract, On Feed - Production, Measured In Head",
  "CHK_BROL_INV": "Chickens, Broilers - Inventory",
  "CHK_BROL_OPS_INV": "Chickens, Broilers - Operations With Inventory",
  "CHK_BROL_SALES_1_1999": "Chickens, Broilers - Operations With Sales - Sales: (1 To 1,999 Head)",
  "CHK_BROL_SALES_10000_199999": "Chickens, Broilers - Operations With Sales - Sales: (100,000 To 199,999 Head)",
  "CHK_BROL_SALES_2000_59999": "Chickens, Broilers - Operations With Sales - Sales: (2,000 To 59,999 Head)",
  "CHK_BROL_SALES_200000_499999": "Chickens, Broilers - Operations With Sales - Sales: (200,000 To 499,999 Head)",
  "CHK_BROL_SALES_500000_PLS": "Chickens, Broilers - Operations With Sales - Sales: (500,000 Or More Head)",
  "CHK_BROL_SALES_60000_99999": "Chickens, Broilers - Operations With Sales - Sales: (60,000 To 99,999 Head)",
  "CHK_BROL_SALES_TOT": "Chickens, Broilers - Operations With Sales",
  "CHK_BROL_SALES_IN_H": "Chickens, Broilers - Sales, Measured In Head",
  "CHK_BROL_PROCON_OPS": "Chickens, Broilers, Production Contract - Operations With Production",
  "CHK_BROL_PROCON_IN_H": "Chickens, Broilers, Production Contract - Production, Measured In Head",
  "CHK_LAY_INV_TOT": "Chickens, Layers - Inventory",
  "CHK_LAY_OPS_INV_1_49": "Chickens, Layers - Operations With Inventory - Inventory: (1 To 49 Head)",
  "CHK_LAY_OPS_INV_10000_19999": "Chickens, Layers - Operations With Inventory - Inventory: (10,000 To 19,999 Head)",
  "CHK_LAY_OPS_INV_100_399": "Chickens, Layers - Operations With Inventory - Inventory: (100 To 399 Head)",
  "CHK_LAY_OPS_INV_100000_PLS": "Chickens, Layers - Operations With Inventory - Inventory: (100,000 Or More Head)",
  "CHK_LAY_OPS_INV_20000_49999": "Chickens, Layers - Operations With Inventory - Inventory: (20,000 To 49,999 Head)",
  "CHK_LAY_OPS_INV_3200_9999": "Chickens, Layers - Operations With Inventory - Inventory: (3,200 To 9,999 Head)",
  "CHK_LAY_OPS_INV_400_3199": "Chickens, Layers - Operations With Inventory - Inventory: (400 To 3,199 Head)",
  "CHK_LAY_OPS_INV_50_99": "Chickens, Layers - Operations With Inventory - Inventory: (50 To 99 Head)",
  "CHK_LAY_OPS_INV_50000_99999": "Chickens, Layers - Operations With Inventory - Inventory: (50,000 To 99,999 Head)",
  "CHK_LAY_OPS_WITH_INV_TOT": "Chickens, Layers - Operations With Inventory",
  "CHK_LAY_OPS_WITH_SALES_TOT": "Chickens, Layers - Operations With Sales",
  "CHK_LAY_SALES_IN_H_TOT": "Chickens, Layers - Sales, Measured In Head",
  "CHK_LAY_PROCON_OPS_WITH_PROD": "Chickens, Layers, Production Contract - Operations With Production",
  "CHK_LAY_PROCON_PROD_IN_H": "Chickens, Layers, Production Contract - Production, Measured In Head",
  "CHK_PULL_RPLT_INV_TOT": "Chickens, Pullets, Replacement - Inventory",
  "CHK_PULL_RPLT_OPS_INV_TOT": "Chickens, Pullets, Replacement - Operations With Inventory",
  "CHK_PULL_RPLT_OPS_SALES_TOT": "Chickens, Pullets, Replacement - Operations With Sales",
  "CHK_PULL_RPLT_SALES_HEAD_TOT": "Chickens, Pullets, Replacement - Sales, Measured In Head",
  "CHK_PULL_RPLT_PROCON_OPS_PROD": "Chickens, Pullets, Replacement, Production Contract - Operations With Production",
  "CHK_PULL_RPLT_PROCON_PROD_IN_H": "Chickens, Pullets, Replacement, Production Contract - Production, Measured In Head",
  "CHK_ROO_INV_TOT": "Chickens, Roosters - Inventory",
  "CHK_ROO_OPS_WITH_INV_TOT": "Chickens, Roosters - Operations With Inventory",
  "CHK_ROO_OPS_WITH_SALES_TOT": "Chickens, Roosters - Operations With Sales",
  "CHK_ROO_SALES_IN_H_TOT": "Chickens, Roosters - Sales, Measured In Head",
  "CORN_SALES_TOT": "Corn - Operations With Sales",
  "CORN_SALES_IN_DOL_TOT": "Corn - Sales, Measured In US Dollars ($)",
  "CORN_GRN_ACRES_HVSD_TOT": "Corn, Grain - Acres Harvested",
  "CORN_GRN_OPS_AREA_HVSD_1000_PL": "Corn, Grain - Operations With Area Harvested - Area Harvested: (1,000 Or More Acres)",
  "CORN_GRN_OPS_AREA_HVSD_1_24_9": "Corn, Grain - Operations With Area Harvested - Area Harvested: (1.0 To 24.9 Acres)",
  "CORN_GRN_OPS_AREA_HVSD_100_249": "Corn, Grain - Operations With Area Harvested - Area Harvested: (100 To 249 Acres)",
  "CORN_GRN_OPS_AREA_HVSD_25_99_9": "Corn, Grain - Operations With Area Harvested - Area Harvested: (25.0 To 99.9 Acres)",
  "CORN_GRN_OPS_AREA_HVSD_250_499": "Corn, Grain - Operations With Area Harvested - Area Harvested: (250 To 499 Acres)",
  "CORN_GRN_OPS_AREA_HVSD_500_999": "Corn, Grain - Operations With Area Harvested - Area Harvested: (500 To 999 Acres)",
  "CORN_GRN_OPS_AREA_HVSD_TOT": "Corn, Grain - Operations With Area Harvested",
  "CORN_GRN_PROD_IN_BU_TOT": "Corn, Grain - Production, Measured In Bushels",
  "CORN_GRN_IRRD_ACRES_HVSD_TOT": "Corn, Grain, Irrigated - Acres Harvested",
  "CORN_GRN_IRRD_OPS_AREA_HVSD_TOT": "Corn, Grain, Irrigated - Operations With Area Harvested",
  "CORN_SLGE_ACRES_HVSD_TOT": "Corn, Silage - Acres Harvested",
  "CORN_SLGE_OPS_AREA_HVSD_1000_PL": "Corn, Silage - Operations With Area Harvested - Area Harvested: (1,000 Or More Acres)",
  "CORN_SLGE_OPS_AREA_HVSD_1_24_9": "Corn, Silage - Operations With Area Harvested - Area Harvested: (1.0 To 24.9 Acres)",
  "CORN_SLGE_OPS_AREA_HVSD_100_249": "Corn, Silage - Operations With Area Harvested - Area Harvested: (100 To 249 Acres)",
  "CORN_SLGE_OPS_AREA_HVSD_25_99": "Corn, Silage - Operations With Area Harvested - Area Harvested: (25.0 To 99.9 Acres)",
  "CORN_SLGE_OPS_AREA_HVSD_250_499": "Corn, Silage - Operations With Area Harvested - Area Harvested: (250 To 499 Acres)",
  "CORN_SLGE_OPS_AREA_HVSD_500_999": "Corn, Silage - Operations With Area Harvested - Area Harvested: (500 To 999 Acres)",
  "CORN_SLGE_OPS_AREA_HVSD_TOT": "Corn, Silage - Operations With Area Harvested",
  "CORN_SLGE_PROD_IN_TONS_TOT": "Corn, Silage - Production, Measured In Tons",
  "CORN_SLGE_IRRD_ACRES_HVSD_TOT": "Corn, Silage, Irrigated - Acres Harvested",
  "CORN_SLGE_IRRD_OPS_A_HVSD_TOT": "Corn, Silage, Irrigated - Operations With Area Harvested",
  "CORN_TDRLIND_ACRES_HVSD_TOT": "Corn, Traditional Or Indian - Acres Harvested",
  "CORN_TDRLIND_OPS_AREA_HVSD_TOT": "Corn, Traditional Or Indian - Operations With Area Harvested",
  "CORN_TDRLIND_PROD_IN_LB_TOT": "Corn, Traditional Or Indian - Production, Measured In Lbs",
  "CORN_TDRLIND_IRRD_HVSD_TOT": "Corn, Traditional Or Indian, Irrigated - Acres Harvested",
  "CORN_TDRLIND_IRRD_OPS_HVSD_TOT": "Corn, Traditional Or Indian, Irrigated - Operations With Area Harvested",
  "COTTON_ACRES_HVSD_TOT": "Cotton - Acres Harvested",
  "COTTON_OPS_W_AREA_HVSD_1000_PLS": "Cotton - Operations With Area Harvested - Area Harvested: (1,000 Or More Acres)",
  "COTTON_OPS_W_AREA_HVSD_1_24_9": "Cotton - Operations With Area Harvested - Area Harvested: (1.0 To 24.9 Acres)",
  "COTTON_OPS_W_AREA_HVSD_100_249": "Cotton - Operations With Area Harvested - Area Harvested: (100 To 249 Acres)",
  "COTTON_OPS_W_AREA_HVSD_25_99_9": "Cotton - Operations With Area Harvested - Area Harvested: (25.0 To 99.9 Acres)",
  "COTTON_OPS_W_AREA_HVSD_250_499": "Cotton - Operations With Area Harvested - Area Harvested: (250 To 499 Acres)",
  "COTTON_OPS_W_AREA_HVSD_500_999": "Cotton - Operations With Area Harvested - Area Harvested: (500 To 999 Acres)",
  "COTTON_OPS_W_AREA_HVSD_TOT": "Cotton - Operations With Area Harvested",
  "COTTON_PROD_IN_BALES_TOT": "Cotton - Production, Measured In Bales",
  "COTTON_IRRD_ACRES_HVSD_TOT": "Cotton, Irrigated - Acres Harvested",
  "COTTON_IRRD_OPS_W_AREA_HVSD_TOT": "Cotton, Irrigated - Operations With Area Harvested",
  "COTTON_L_S_OPS_W_SALES_TOT": "Cotton, Lint & Seed - Operations With Sales",
  "COTTON_L_S_SALES_IN_DOL_TOT": "Cotton, Lint & Seed - Sales, Measured In US Dollars ($)",
  "COTTON_PIMA_ACRES_HVSD_TOT": "Cotton, Pima - Acres Harvested",
  "COTTON_PIMA_OPS_W_A_HVSD_TOT": "Cotton, Pima - Operations With Area Harvested",
  "COTTON_PIMA_PROD_IN_BALES_TOT": "Cotton, Pima - Production, Measured In Bales",
  "COTTON_PIMA_IRR_ACRES_HVSD_TOT": "Cotton, Pima, Irrigated - Acres Harvested",
  "COTTON_PIMA_IRR_OPS_A_HVSD_TOT": "Cotton, Pima, Irrigated - Operations With Area Harvested",
  "COTTON_UPLD_ACRES_HVSD_TOT": "Cotton, Upland - Acres Harvested",
  "COTTON_UPLD_OPS_W_A_HVSD_TOT": "Cotton, Upland - Operations With Area Harvested",
  "COTTON_UPLD_PROD_IN_BALES_TOT": "Cotton, Upland - Production, Measured In Bales",
  "COTTON_UPLD_IRRD_ACRES_HVSD_TOT": "Cotton, Upland, Irrigated - Acres Harvested",
  "COTTON_UPLD_IRR_OPS_W_A_HVD_TOT": "Cotton, Upland, Irrigated - Operations With Area Harvested",
  "CROP_TOT_OPS_W_SALES_TOT": "Crop Totals - Operations With Sales",
  "CROP_TOT_SALES_IN_DOL_TOT": "Crop Totals - Sales, Measured In US Dollars ($)",
  "CROP_TOT_PRODCON_OPS_W_PROD_TOT": "Crop Totals, Production Contract - Operations With Production",
  "FRM_OPS_AC_OPD_AREA_OPD_1K_1999": "Farm Operations - Acres Operated - Area Operated: (1,000 To 1,999 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_1_9_9": "Farm Operations - Acres Operated - Area Operated: (1.0 To 9.9 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_10_49_9": "Farm Operations - Acres Operated - Area Operated: (10.0 To 49.9 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_100_139": "Farm Operations - Acres Operated - Area Operated: (100 To 139 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_140_179": "Farm Operations - Acres Operated - Area Operated: (140 To 179 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_180_219": "Farm Operations - Acres Operated - Area Operated: (180 To 219 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_2K_PLS": "Farm Operations - Acres Operated - Area Operated: (2,000 Or More Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_220_259": "Farm Operations - Acres Operated - Area Operated: (220 To 259 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_260_499": "Farm Operations - Acres Operated - Area Operated: (260 To 499 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_50_69_9": "Farm Operations - Acres Operated - Area Operated: (50.0 To 69.9 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_500_999": "Farm Operations - Acres Operated - Area Operated: (500 To 999 Acres)",
  "FRM_OPS_AC_OPD_AREA_OPD_70_99_9": "Farm Operations - Acres Operated - Area Operated: (70.0 To 99.9 Acres)",
  "FRM_OPS_AC_OPD_TNR_FULL_OWNER": "Farm Operations - Acres Operated - Tenure: (Full Owner)",
  "FRM_OPS_AC_OPD_TNR_PART_OWNER": "Farm Operations - Acres Operated - Tenure: (Part Owner)",
  "FRM_OPS_AC_OPD_TNR_TENANT": "Farm Operations - Acres Operated - Tenure: (Tenant)",
  "FRM_OPS_AC_OPD_TOT": "Farm Operations - Acres Operated - Total",
  "FRM_OPS_AREA_OPD_IN_AC_P_OP_TOT": "Farm Operations - Area Operated, Measured In Acres / Operation - Total",
  "FRM_OPS_AREA_OPD_IN_AC_P_OP_AVG": "Farm Operations - Area Operated, Measured In Acres / Operation, Median - Total",
  "FRM_OPS_AREA_OPD_IN_PCT_TOT": "Farm Operations - Area Operated, Measured In Pct Of Total Land - Total",
  "FRM_OPS_NUM_OF_OPS_AC_1K_PLS": "Farm Operations - Number Of Operations - Area Operated: (1,000 Or More Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_1K_1999": "Farm Operations - Number Of Operations - Area Operated: (1,000 To 1,999 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_1_9_9": "Farm Operations - Number Of Operations - Area Operated: (1.0 To 9.9 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_10_49_9": "Farm Operations - Number Of Operations - Area Operated: (10.0 To 49.9 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_100_139": "Farm Operations - Number Of Operations - Area Operated: (100 To 139 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_140_179": "Farm Operations - Number Of Operations - Area Operated: (140 To 179 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_180_219": "Farm Operations - Number Of Operations - Area Operated: (180 To 219 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_180_499": "Farm Operations - Number Of Operations - Area Operated: (180 To 499 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_2K_PLS": "Farm Operations - Number Of Operations - Area Operated: (2,000 Or More Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_220_259": "Farm Operations - Number Of Operations - Area Operated: (220 To 259 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_260_499": "Farm Operations - Number Of Operations - Area Operated: (260 To 499 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_50_179": "Farm Operations - Number Of Operations - Area Operated: (50 To 179 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_50_69_9": "Farm Operations - Number Of Operations - Area Operated: (50.0 To 69.9 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_500_999": "Farm Operations - Number Of Operations - Area Operated: (500 To 999 Acres)",
  "FRM_OPS_NUM_OF_OPS_AC_70_99_9": "Farm Operations - Number Of Operations - Area Operated: (70.0 To 99.9 Acres)",
  "FRM_OPS_NUM_OF_OPS_NAICS_1111": "Farm Operations - Number Of Operations - Naics Classification: (1111)",
  "FRM_OPS_NUM_OF_OPS_NAICS_1112": "Farm Operations - Number Of Operations - Naics Classification: (1112)",
  "FRM_OPS_NUM_OF_OPS_NAICS_1113": "Farm Operations - Number Of Operations - Naics Classification: (1113)",
  "FRM_OPS_NUM_OF_OPS_NAICS_1114": "Farm Operations - Number Of Operations - Naics Classification: (1114)",
  "FRM_OPS_NUM_OF_OPS_NAICS_1119": "Farm Operations - Number Of Operations - Naics Classification: (1119)",
  "FRM_OPS_NUM_OF_OPS_NAICS_11191": "Farm Operations - Number Of Operations - Naics Classification: (11191)",
  "FRM_OPS_NUM_OF_OPS_NAICS_11192": "Farm Operations - Number Of Operations - Naics Classification: (11192)",
  "FRM_OPS_NUM_OF_OPS_11193_94_99": "Farm Operations - Number Of Operations - Naics Classification: (11193 & 11194 & 11199)",
  "FRM_OPS_NUM_OF_OPS_NAICS_112111": "Farm Operations - Number Of Operations - Naics Classification: (112111)",
  "FRM_OPS_NUM_OF_OPS_NAICS_112112": "Farm Operations - Number Of Operations - Naics Classification: (112112)",
  "FRM_OPS_NUM_OF_OPS_NAICS_11212": "Farm Operations - Number Of Operations - Naics Classification: (11212)",
  "FRM_OPS_NUM_OF_OPS_NAICS_1122": "Farm Operations - Number Of Operations - Naics Classification: (1122)",
  "FRM_OPS_NUM_OF_OPS_NAICS_1123": "Farm Operations - Number Of Operations - Naics Classification: (1123)",
  "FRM_OPS_NUM_OF_OPS_NAICS_1124": "Farm Operations - Number Of Operations - Naics Classification: (1124)",
  "FRM_OPS_NUM_OF_OPS_1125_1129": "Farm Operations - Number Of Operations - Naics Classification: (1125 & 1129)",
  "FRM_OPS_NUM_OF_OPS_TNR_TNR_FULL": "Farm Operations - Number Of Operations - Tenure: (Full Owner)",
  "FRM_OPS_NUM_OF_OPS_TNR_TNR_PART": "Farm Operations - Number Of Operations - Tenure: (Part Owner)",
  "FRM_OPS_NUM_OF_OPS_TNR_TNR_TNT": "Farm Operations - Number Of Operations - Tenure: (Tenant)",
  "FRM_OPS_NUM_OF_OPS_TOT": "Farm Operations - Number Of Operations - Total",
  "FRM_OPS_AWR_TO_APPL_NUM_OPS_TOT": "Farm Operations, Aware Of Right To Appeal Adverse Decisions To Usda Nad - Number Of Operations - Total",
  "FRM_OPS_ORG_NUM_OF_OPS_CERT": "Farm Operations, Organic - Number Of Operations - Organic Status: (Nop Usda Certified)",
  "FRM_OPS_ORG_NUM_OF_OPS_EXMT": "Farm Operations, Organic - Number Of Operations - Organic Status: (Nop Usda Exempt)",
  "FRM_OPS_ORG_GT50_PCT_1_HH_AC_T": "Farm Operations, Organization, Gt 50 Pct Ownership Held By One Producers Household & Extended Family - Acres Operated - Total",
  "FRM_OPS_ORG_GT50_PCT_1_HH_OPS_T": "Farm Operations, Organization, Gt 50 Pct Ownership Held By One Producers Household & Extended Family - Operations With Area Operated - Total",
  "FRM_OPS_ORG_LLC_AC_OP_TOT": "Farm Operations, Organization, Limited Liability Company - Acres Operated - Total",
  "FRM_OPS_ORG_LLC_NUM_OPS_TOT": "Farm Operations, Organization, Limited Liability Company - Number Of Operations - Total",
  "FRM_OPS_ORG_EX_FAM_AC_OPS_T": "Farm Operations, Organization, Tax Purposes, Corporation, (Excl Family Held) - Acres Operated - Total",
  "FRM_OPS_ORG_EX_FAM_NUM_OPS_T": "Farm Operations, Organization, Tax Purposes, Corporation, (Excl Family Held) - Number Of Operations - Total",
  "FRM_OPS_ORG_FAM_AC_OPS_T": "Farm Operations, Organization, Tax Purposes, Corporation, Family Held - Acres Operated - Total",
  "FRM_OPS_ORG_FAM_NUM_OPS_T": "Farm Operations, Organization, Tax Purposes, Corporation, Family Held - Number Of Operations - Total",
  "FRM_OPS_ORG_FAM_IND_AC_OPS_T": "Farm Operations, Organization, Tax Purposes, Family & Individual - Acres Operated - Total",
  "FRM_OPS_ORG_FAM_IND_NUM_OPS_T": "Farm Operations, Organization, Tax Purposes, Family & Individual - Number Of Operations - Total",
  "FRM_OPS_ORG_R_R_AC_OPS_T": "Farm Operations, Organization, Tax Purposes, Institutional & Research & Reservation & Other - Acres Operated - Total",
  "FRM_OPS_ORG_R_R_NUM_OPS_T": "Farm Operations, Organization, Tax Purposes, Institutional & Research & Reservation & Other - Number Of Operations - Total",
  "FRM_OPS_ORG_TAX_PUR_PRT_AC": "Farm Operations, Organization, Tax Purposes, Partnership - Acres Operated - Total",
  "FRM_OPS_ORG_TAX_PUR_PRT_NUM_OPS": "Farm Operations, Organization, Tax Purposes, Partnership - Number Of Operations - Total",
  "GOVT_PRG_FED_OPS_W_RCPTS": "Govt Programs, Federal - Operations With Receipts",
  "GOVT_PRG_FED_RCPTS_DOL_OPS": "Govt Programs, Federal - Receipts, Measured In US Dollars ($) / Operation",
  "GOVT_PRG_FED_RCPTS_DOL_TOT": "Govt Programs, Federal - Receipts, Measured In US Dollars ($)",
  "GOVT_PRG_FED_EX_CSVR_OPS_RCPT": "Govt Programs, Federal, (Excl Conservation & Wetlands) - Operations With Receipts",
  "GOVT_PRG_FED_EX_CSVR_RCPT_DOLOP": "Govt Programs, Federal, (Excl Conservation & Wetlands) - Receipts, Measured In US Dollars ($) / Operation",
  "GOVT_PRG_FED_EX_CSVR_RCPT_DOL": "Govt Programs, Federal, (Excl Conservation & Wetlands) - Receipts, Measured In US Dollar ($)",
  "GOVT_PRG_FED_CSVR_ACRES_TOT": "Govt Programs, Federal, Conservation & Wetlands - Acres",
  "GOVT_PRG_FED_CSVR_NUM_OPS": "Govt Programs, Federal, Conservation & Wetlands - Number Of Operations",
  "GOVT_PRG_FED_CSVR_OPS_RCPT": "Govt Programs, Federal, Conservation & Wetlands - Operations With Receipts",
  "GOVT_PRG_FED_CSVR_RCPT_DOLOPS": "Govt Programs, Federal, Conservation & Wetlands - Receipts, Measured In US Dollars ($) / Operation",
  "GOVT_PRG_FED_CSVR_RCPT_DOL": "Govt Programs, Federal, Conservation & Wetlands - Receipts, Measured In US Dollars ($)",
  "GRN_OPS_W_SALES_TOT": "Grain - Operations With Sales",
  "GRN_SALES_DOL_TOT": "Grain - Sales, Measured In US Dollars ($)",
  "GRN_OTHER_OPS_W_SALES_TOT": "Grain, Other - Operations With Sales",
  "GRN_OTHER_SALES_DOL_TOT": "Grain, Other - Sales, Measured In US Dollars ($)",
  "GRAPES_ACRES_BEAR_NON_BEAR_TOT": "Grapes - Acres Bearing & Non-Bearing",
  "GRAPES_ACRES_BEAR_TOT": "Grapes - Acres Bearing",
  "GRAPES_ACRES_NON_BEA_TOT": "Grapes - Acres Non-Bearing",
  "GRAPES_OPS_AREA_BEARNONBEAR_TOT": "Grapes - Operations With Area Bearing & Non-Bearing",
  "GRAPES_OPS_AREA_BEAR_TOT": "Grapes - Operations With Area Bearing",
  "GRAPES_OPS_AREA_NON_BEAR_TOT": "Grapes - Operations With Area Non-Bearing",
  "HAY_ACRES_HVSD_TOT": "Hay - Acres Harvested",
  "HAY_OPS_WAREA_HVSD_TOT": "Hay - Operations With Area Harvested",
  "HAY_PROD_IN_TONS_TOT": "Hay - Production, Measured In Tons",
  "HAY_EXCL_ALFA_ACRES_HVSD_TOT": "Hay, (Excl Alfalfa) - Acres Harvested",
  "HAY_EXCL_ALFA_OPS_WAREA_HVD_TOT": "Hay, (Excl Alfalfa) - Operations With Area Harvested",
  "HAY_EXCL_ALFA_PROD_TONS_TOT": "Hay, (Excl Alfalfa) - Production, Measured In Tons",
  "HAY_EXCL_ALFA_IRR_ACRES_HVD_TOT": "Hay, (Excl Alfalfa), Irrigated - Acres Harvested",
  "HAY_EXCL_ALFA_IRRD_OPS_AREA_HVD": "Hay, (Excl Alfalfa), Irrigated - Operations With Area Harvested",
  "HAY_ALFA_ACRES_HVSD_TOT": "Hay, Alfalfa - Acres Harvested",
  "HAY_ALFA_OPS_WAREA_HVSD_TOT": "Hay, Alfalfa - Operations With Area Harvested",
  "HAY_ALFA_PROD_TONS_TOT": "Hay, Alfalfa - Production, Measured In Tons",
  "HAY_ALFA_IRRD_ACRES_HVSD_TOT": "Hay, Alfalfa, Irrigated - Acres Harvested",
  "HAY_ALFA_IRRD_OPS_WAREA_HVD_TOT": "Hay, Alfalfa, Irrigated - Operations With Area Harvested",
  "HAY_IRRD_ACRES_HVSD_TOT": "Hay, Irrigated - Acres Harvested",
  "HAY_IRRD_OPS_WAREA_HVSD_TOT": "Hay, Irrigated - Operations With Area Harvested",
  "HOGS_INV_OF_HOGS_1_24": "Hogs - Inventory - Inventory Of Hogs: (1 To 24 Head)",
  "HOGS_INV_OF_HOGS_1000_PLS": "Hogs - Inventory - Inventory Of Hogs: (1,000 Or More Head)",
  "HOGS_INV_OF_HOGS_100_199": "Hogs - Inventory - Inventory Of Hogs: (100 To 199 Head)",
  "HOGS_INV_OF_HOGS_200_499": "Hogs - Inventory - Inventory Of Hogs: (200 To 499 Head)",
  "HOGS_INV_OF_HOGS_25_49": "Hogs - Inventory - Inventory Of Hogs: (25 To 49 Head)",
  "HOGS_INV_OF_HOGS_50_99": "Hogs - Inventory - Inventory Of Hogs: (50 To 99 Head)",
  "HOGS_INV_OF_HOGS_500_999": "Hogs - Inventory - Inventory Of Hogs: (500 To 999 Head)",
  "HOGS_INV_TOT": "Hogs - Inventory",
  "HOGS_OPS_W_INV_1_24": "Hogs - Operations With Inventory - Inventory Of Hogs: (1 To 24 Head)",
  "HOGS_OPS_W_INV_1000_PLS": "Hogs - Operations With Inventory - Inventory Of Hogs: (1,000 Or More Head)",
  "HOGS_OPS_W_INV_100_199": "Hogs - Operations With Inventory - Inventory Of Hogs: (100 To 199 Head)",
  "HOGS_OPS_W_INV_200_499": "Hogs - Operations With Inventory - Inventory Of Hogs: (200 To 499 Head)",
  "HOGS_OPS_W_INV_25_49": "Hogs - Operations With Inventory - Inventory Of Hogs: (25 To 49 Head)",
  "HOGS_OPS_W_INV_50_99": "Hogs - Operations With Inventory - Inventory Of Hogs: (50 To 99 Head)",
  "HOGS_OPS_W_INV_500_999": "Hogs - Operations With Inventory - Inventory Of Hogs: (500 To 999 Head)",
  "HOGS_OPS_W_INV_TOT": "Hogs - Operations With Inventory",
  "HOGS_OPS_W_SALES_1_24": "Hogs - Operations With Sales - Sales Of Hogs: (1 To 24 Head)",
  "HOGS_OPS_W_SALES_1000_PLS": "Hogs - Operations With Sales - Sales Of Hogs: (1,000 Or More Head)",
  "HOGS_OPS_W_SALES_100_199": "Hogs - Operations With Sales - Sales Of Hogs: (100 To 199 Head)",
  "HOGS_OPS_W_SALES_200_499": "Hogs - Operations With Sales - Sales Of Hogs: (200 To 499 Head)",
  "HOGS_OPS_W_SALES_25_49": "Hogs - Operations With Sales - Sales Of Hogs: (25 To 49 Head)",
  "HOGS_OPS_W_SALES_50_99": "Hogs - Operations With Sales - Sales Of Hogs: (50 To 99 Head)",
  "HOGS_OPS_W_SALES_500_999": "Hogs - Operations With Sales - Sales Of Hogs: (500 To 999 Head)",
  "HOGS_OPS_W_SALES_TOT": "Hogs - Operations With Sales",
  "HOGS_SALES_IN_DOL_TOT": "Hogs - Sales, Measured In US Dollars ($)",
  "HOGS_SALES_IN_H_1_24": "Hogs - Sales, Measured In Head - Sales Of Hogs: (1 To 24 Head)",
  "HOGS_SALES_IN_H_1000_PLS": "Hogs - Sales, Measured In Head - Sales Of Hogs: (1,000 Or More Head)",
  "HOGS_SALES_IN_H_100_199": "Hogs - Sales, Measured In Head - Sales Of Hogs: (100 To 199 Head)",
  "HOGS_SALES_IN_H_200_499": "Hogs - Sales, Measured In Head - Sales Of Hogs: (200 To 499 Head)",
  "HOGS_SALES_IN_H_25_49": "Hogs - Sales, Measured In Head - Sales Of Hogs: (25 To 49 Head)",
  "HOGS_SALES_IN_H_50_99": "Hogs - Sales, Measured In Head - Sales Of Hogs: (50 To 99 Head)",
  "HOGS_SALES_IN_H_500_999": "Hogs - Sales, Measured In Head - Sales Of Hogs: (500 To 999 Head)",
  "HOGS_SALES_IN_H_TOT": "Hogs - Sales, Measured In Head",
  "HOGS_PRODCON_OPS_W_PROD_TOT": "Hogs, Production Contract - Operations With Production",
  "HOGS_PRODCON_PROD_IN_H_TOT": "Hogs, Production Contract - Production, Measured In Head",
  "LBR_CON_EXP_DOL_TOT": "Labor, Contract - Expense, Measured In US Dollars ($)",
  "LBR_CON_OPS_W_EXP_TOT": "Labor, Contract - Operations With Expense",
  "LBR_HRD_EXP_DOL_GELT150": "Labor, Hired - Expense, Measured In US Dollars ($) - Labor: (Hired Workers >= 150 Days & < 150 Days)",
  "LBR_HRD_EXP_DOL_TOT": "Labor, Hired - Expense, Measured In US Dollars ($)",
  "LBR_HRD_NUMWKRS_1_4": "Labor, Hired - Number Of Workers - Labor: (1 To 4 Hired Workers)",
  "LBR_HRD_NUMWKRS_10_PLS": "Labor, Hired - Number Of Workers - Labor: (10 Or More Hired Workers)",
  "LBR_HRD_NUMWKRS_5_9": "Labor, Hired - Number Of Workers - Labor: (5 To 9 Hired Workers)",
  "LBR_HRD_NUMWKRS_TOT": "Labor, Hired - Number Of Workers",
  "LBR_HRD_OPS_W_EXP_TOT": "Labor, Hired - Operations With Expense",
  "LBR_HRD_OPS_W_WKRS_1_4": "Labor, Hired - Operations With Workers - Labor: (1 To 4 Hired Workers)",
  "LBR_HRD_OPS_W_WKRS_10_PLS": "Labor, Hired - Operations With Workers - Labor: (10 Or More Hired Workers)",
  "LBR_HRD_OPS_W_WKRS_5_9": "Labor, Hired - Operations With Workers - Labor: (5 To 9 Hired Workers)",
  "LBR_HRD_OPS_W_WKRS_GELT150": "Labor, Hired - Operations With Workers - Labor: (Hired Workers >= 150 Days & < 150 Days)",
  "LBR_HRD_OPS_W_WKRS_TOT": "Labor, Hired - Operations With Workers",
  "LBR_HRD_GE150_DOL_WKRS_GE150": "Labor, Hired, >= 150 Days - Expense, Measured In US Dollars ($) - Labor: (Hired Workers >= 150 Days)",
  "LBR_HRD_GE150_NUMWKRS_10_PLS": "Labor, Hired, >= 150 Days - Number Of Workers - Labor: (10 Or More Hired Workers)",
  "LBR_HRD_GE150_NUMWKRS_5_9": "Labor, Hired, >= 150 Days - Number Of Workers - Labor: (5 To 9 Hired Workers)",
  "LBR_HRD_GE150_N_WKRS_GELT150": "Labor, Hired, >= 150 Days - Number Of Workers - Labor: (Hired Workers >= 150 Days & < 150 Days)",
  "LBR_HRD_GE150_NUMWKRS_GE150": "Labor, Hired, >= 150 Days - Number Of Workers - Labor: (Hired Workers >= 150 Days)",
  "LBR_HRD_GE150_D_NUMWKRS_TOT": "Labor, Hired, >= 150 Days - Number Of Workers",
  "LBR_HRD_GE150_OPS_WKRS_10_PLS": "Labor, Hired, >= 150 Days - Operations With Workers - Labor: (10 Or More Hired Workers)",
  "LBR_HRD_GE150_D_OPS_WKRS_5_9": "Labor, Hired, >= 150 Days - Operations With Workers - Labor: (5 To 9 Hired Workers)",
  "LBR_HRD_GE150_D_OPS_WKRS_GE150": "Labor, Hired, >= 150 Days - Operations With Workers - Labor: (Hired Workers >= 150 Days)",
  "LBR_HRD_GE150_D_OPS_WKRS": "Labor, Hired, >= 150 Days - Operations With Workers",
  "LBR_HRD_GT150_D_NUMWKRS_1_4": "Labor, Hired, > 150 Days - Number Of Workers - Labor: (1 To 4 Hired Workers)",
  "LBR_HRD_GT150_D_OPS_W_WKRS_1_4": "Labor, Hired, > 150 Days - Operations With Workers - Labor: (1 To 4 Hired Workers)",
  "LBR_HRD_LT150_D_EXP_DOL_LT150": "Labor, Hired, < 150 Days - Expense, Measured In US Dollars ($) - Labor: (Hired Workers < 150 Days)",
  "LBR_HRD_LT150_D_NUMWKRS_1_4": "Labor, Hired, < 150 Days - Number Of Workers - Labor: (1 To 4 Hired Workers)",
  "LBR_HRD_LT150_D_NUMWKRS_10_PLS": "Labor, Hired, < 150 Days - Number Of Workers - Labor: (10 Or More Hired Workers)",
  "LBR_HRD_LT150_D_NUMWKRS_5_9": "Labor, Hired, < 150 Days - Number Of Workers - Labor: (5 To 9 Hired Workers)",
  "LBR_HRD_LT150_D_NUMWKRS_GELT150": "LBR_HRD_LT150_D_NUMWKRS_GELT150",
  "LBR_HRD_LT150_D_NUMWKRS_LT150": "Labor, Hired, < 150 Days - Number Of Workers - Labor: (Hired Workers < 150 Days)",
  "LBR_HRD_LT150_D_NUMWKRS_TOT": "Labor, Hired, < 150 Days - Number Of Workers",
  "LBR_HRD_LT150_D_OPS_W_WKRS_1_4": "Labor, Hired, < 150 Days - Operations With Workers - Labor: (1 To 4 Hired Workers)",
  "LBR_HRD_LT150_D_OPS_W_WKRS_10_P": "Labor, Hired, < 150 Days - Operations With Workers - Labor: (10 Or More Hired Workers)",
  "LBR_HRD_LT150_D_OPS_W_WKRS_5_9": "Labor, Hired, < 150 Days - Operations With Workers - Labor: (5 To 9 Hired Workers)",
  "LBR_HRD_LT150_D_OPS_W_WKR_LT150": "Labor, Hired, < 150 Days - Operations With Workers - Labor: (Hired Workers < 150 Days)",
  "LBR_HRD_LT150_D_OPS_W_WKRS_TOT": "Labor, Hired, < 150 Days - Operations With Workers",
  "LBR_MIGT_NUMWKRS_INCL_HRD": "Labor, Migrant - Number Of Workers - Labor: (Incl Hired Workers)",
  "LBR_MIGT_NUMWKRS_ONLY_CON": "Labor, Migrant - Number Of Workers - Labor: (Only Contract)",
  "LBR_MIGT_NUMWKRS_TOT": "Labor, Migrant - Number Of Workers",
  "LBR_MIGT_OPS_W_WKRS_INCL_HRD": "Labor, Migrant - Operations With Workers - Labor: (Incl Hired Workers)",
  "LBR_MIGT_OPS_W_WKRS_ONLY_CON": "Labor, Migrant - Operations With Workers - Labor: (Only Contract)",
  "LBR_MIGT_OPS_W_WKRS_TOT": "Labor, Migrant - Operations With Workers",
  "LBR_UNPAID_NUMWKRS_TOT": "Labor, Unpaid - Number Of Workers",
  "LBR_UNPAID_OPS_W_WKRS_TOT": "Labor, Unpaid - Operations With Workers",
  "MACH_TOT_ASTVAL_DOLOPS": "Machinery Totals - Asset Value, Measured In US Dollars ($) / Operation",
  "MACH_TOT_ASTVAL_DOL_TOT": "Machinery Totals - Asset Value, Measured In US Dollars ($)",
  "MACH_TOT_OPS_W_ASTVAL_TOT": "Machinery Totals - Operations With Asset Value",
  "MACH_TOT_OPS_ASTVAL_10000_19999": "Machinery Totals - Operations With Asset Value - Value: (10,000 To 19,999 US Dollars ($))",
  "MACH_TOT_OPS_ASTV_100000_199999": "Machinery Totals - Operations With Asset Value - Value: (100,000 To 199,999 US Dollars ($))",
  "MACH_TOT_OPS_AVAL_20000_29999": "Machinery Totals - Operations With Asset Value - Value: (20,000 To 29,999 US Dollars ($))",
  "MACH_TOT_OPS_AVAL_200000_499999": "Machinery Totals - Operations With Asset Value - Value: (200,000 To 499,999 US Dollars ($))",
  "MACH_TOT_OPS_ASTVAL_30000_49999": "Machinery Totals - Operations With Asset Value - Value: (30,000 To 49,999 US Dollars ($))",
  "MACH_TOT_OPS_ASTVAL_50000_69999": "Machinery Totals - Operations With Asset Value - Value: (50,000 To 69,999 US Dollars ($))",
  "MACH_TOT_OPS_ASTVAL_500000_PLS": "Machinery Totals - Operations With Asset Value - Value: (500,000 Or More US Dollars ($))",
  "MACH_TOT_OPS_ASTVAL_70000_99999": "Machinery Totals - Operations With Asset Value - Value: (70,000 To 99,999 US Dollars ($))",
  "MACH_TOT_OPS_ASTVAL_LT10000": "Machinery Totals - Operations With Asset Value - Value: (Less Than 10,000 US Dollars ($))",
  "MILK_OPS_W_SALES": "Milk - Operations With Sales",
  "MILK_SALES_IN_DOL_TOT": "Milk - Sales, Measured In US Dollars ($)",
  "PRODS_AGE_AVG_IN_YRS_TOT": "Producers - Average Age In Years",
  "PRODS_NUM_OF_OPS_PRODS_1_FEM": "Producers - Number Of Operations: (1 Female Producers)",
  "PRODS_NUM_OF_OPS_PRODS_1_MAL": "Producers - Number Of Operations: (1 Male Producers)",
  "PRODS_NUM_OF_OPS_PRODS_1_PRO": "Producers - Number Of Operations: (1 Producers)",
  "PRODS_NUM_OF_OPS_PRODS_2_FEM": "Producers - Number Of Operations: (2 Female Producers)",
  "PRODS_NUM_OF_OPS_PRODS_2_MAL": "Producers - Number Of Operations: (2 Male Producers)",
  "PRODS_NUM_OF_OPS_PRODS_2_PRO": "Producers - Number Of Operations: (2 Producers)",
  "PRODS_NUM_OF_OPS_PRODS_3_FEM": "Producers - Number Of Operations: (3 Female Producers)",
  "PRODS_NUM_OF_OPS_PRODS_3_MAL": "Producers - Number Of Operations: (3 Male Producers)",
  "PRODS_NUM_OF_OPS_PRODS_3_PRO": "Producers - Number Of Operations: (3 Producers)",
  "PRODS_NUM_OF_OPS_PRODS_4_FEM": "Producers - Number Of Operations: (4 Female Producers)",
  "PRODS_NUM_OF_OPS_PRODS_4_MAL": "Producers - Number Of Operations: (4 Male Producers)",
  "PRODS_NUM_OF_OPS_PRODS_4_PRO": "Producers - Number Of Operations: (4 Producers)",
  "PRODS_NUM_OF_OPS_PRODS_5PLSFEM": "Producers - Number Of Operations: (5 Or More Female Producers)",
  "PRODS_NUM_OF_OPS_PRODS_5PLSMAL": "Producers - Number Of Operations: (5 Or More Male Producers)",
  "PRODS_NUM_OF_OPS_PRODS_5PLSPRO": "Producers - Number Of Operations: (5 Or More Producers)",
  "PRODS_NUM_OF_PRODS_TOT": "Producers - Number Of Producers",
  "PRODS_PRSN_IN_HH_IN_PRSN_TOT": "Producers - Persons In Household - Measured In Persons",
  "PRODS_YRS_ANY_OPR_AVG_YRS_TOT": "Producers - Years On Any Operation - Avg - Measured In Years",
  "PRODS_YRS_PRST_OPR_AVG_YRS": "Producers - Years On Present Operation - Avg - Measured In Years",
  "PRODS_ALL_NUM_OF_PRODS_TOT": "Producers - (All) - Number Of Producers",
  "PRODS_ALL_FEM_NUM_OF_PRODS_TOT": "Producers - (All) - Female - Number Of Producers",
  "PRODS_ALL_MAL_NUM_OF_PRODS_TOT": "Producers - (All) - Male - Number Of Producers",
  "PRODS_AGE_25_TO_34_NUMPRODS_TOT": "Producers - Age 25 To 34 - Number Of Producers",
  "PRODS_AGE_35_TO_44_NUMPRODS_TOT": "Producers - Age 35 To 44 - Number Of Producers",
  "PRODS_AGE_45_TO_54_NUMPRODS_TOT": "Producers - Age 45 To 54 - Number Of Producers",
  "PRODS_AGE_55_TO_64_NUMPRODS_TOT": "Producers - Age 55 To 64 - Number Of Producers",
  "PRODS_AGE_65_TO_74_NUMPRODS_TOT": "Producers - Age 65 To 74 - Number Of Producers",
  "PRODS_AGE_GE_75_NUMPRODS_TOT": "Producers - Age Ge 75 - Number Of Producers",
  "PRODS_AGE_LT_25_NUMPRODS_TOT": "Producers - Age Lt 25 - Number Of Producers",
  "PRODS_AGE_LT_35_AC_OPD_TOT": "Producers - Age Lt 35 - Acres Operated",
  "PRODS_AGE_LT_35_NUM_OF_OPS_TOT": "Producers - Age Lt 35 - Number Of Operations",
  "PRODS_AGE_LT_35_NUM_PRODS_TOT": "Producers - Age Lt 35 - Number Of Producers",
  "PRODS_AMR_IND_AK_NTV_AC_OPD_TO": "Producers - American Indian Or Alaska Native - Acres Operated",
  "PRODS_AMR_IND_AK_NTV_NUM_OF_OPS": "Producers - American Indian Or Alaska Native - Number Of Operations",
  "PRODS_AMR_IND_AK_NTV_NUM": "Producers - American Indian Or Alaska Native - Number Of Producers",
  "PRODS_ASN_AC_OPD_TOT": "Producers - Asian - Acres Operated",
  "PRODS_ASN_NUM_OF_OPS_TOT": "Producers - Asian - Number Of Operations",
  "PRODS_ASN_NUM_OF_PRODS_TOT": "Producers - Asian - Number Of Producers",
  "PRODS_ASN_CHN_AC_OPD_TOT": "Producers - Asian - Chinese - Acres Operated",
  "PRODS_ASN_CHN_NUM_OF_OPS_TOT": "Producers - Asian - Chinese - Number Of Operations",
  "PRODS_ASN_CHN_NUM_OF_PRODS_TOT": "Producers - Asian - Chinese - Number Of Producers",
  "PRODS_ASN_FIL_AC_OPD_TOT": "Producers - Asian - Filipino - Acres Operated",
  "PRODS_ASN_FIL_NUM_OF_OPS_TOT": "Producers - Asian - Filipino - Number Of Operations",
  "PRODS_ASN_FIL_NUM_OF_PRODS_TOT": "Producers - Asian - Filipino - Number Of Producers",
  "PRODS_ASN_JPN_AC_OPD_TOT": "Producers - Asian - Japanese - Acres Operated",
  "PRODS_ASN_JPN_NUM_OF_OPS_TOT": "Producers - Asian - Japanese - Number Of Operations",
  "PRODS_ASN_JPN_NUM_OF_PRODS_TOT": "Producers - Asian - Japanese - Number Of Producers",
  "PRODS_ASN_KOR_AC_OPD_TOT": "Producers - Asian - Korean - Acres Operated",
  "PRODS_ASN_KOR_NUM_OF_OPS_TOT": "Producers - Asian - Korean - Number Of Operations",
  "PRODS_ASN_KOR_NUM_OF_PRODS_TOT": "Producers - Asian - Korean - Number Of Producers",
  "PRODS_ASN_OTR_AC_OPD_TOT": "Producers - Asian - Other - Acres Operated",
  "PRODS_ASN_OTR_NUM_OF_OPS_TOT": "Producers - Asian - Other - Number Of Operations",
  "PRODS_ASN_OTR_NUM_OF_PRODS_TOT": "Producers - Asian - Other - Number Of Producers",
  "PRODS_BLK_OR_AFR_AMR_AC_OPD_TOT": "Producers - Black Or African American - Acres Operated",
  "PRODS_BLK_AFR_AMR_NUM_OF_OPS_TO": "Producers - Black Or African American - Number Of Operations",
  "PRODS_BLK_AFR_AMR_NUM_PRODS_TOT": "Producers - Black Or African American - Number Of Producers",
  "PRODS_DY_DEC_MKG_NUM_PRODS_TOT": "Producers - Day To Day Decisionmaking - Number Of Producers",
  "PRODS_DYS_WKD_OFF_OPR_0_TOT": "Producers - Days Worked Off Operation - 0 Days - Number Of Producers",
  "PRODS_DYS_WKD_OFF_OPR_1_49_TOT": "Producers - Days Worked Off Operation - 1 To 49 Days - Number Of Producers",
  "PRODS_D_WKD_OFF_OPR_100_199_TOT": "Producers - Days Worked Off Operation - 100 To 199 Days - Number Of Producers",
  "PRODS_DYS_WKD_OFF_OPR_50_99_TOT": "Producers - Days Worked Off Operation - 50 To 99 Days - Number Of Producers",
  "PRODS_DYS_WKD_OFF_OPR_GE_1_TOT": "Producers - Days Worked Off Operation - Ge 1 Days - Number Of Producers",
  "PRODS_D_WKD_OFF_OPR_GE_200_TOT": "Producers - Days Worked Off Operation - Ge 200 Days - Number Of Producers",
  "PRODS_ESTE_SUCC_PLNG_DMKG_NUM": "Producers - Estate Or Succession Planning Decisionmaking - Number Of Producers",
  "PRODS_FEM_AC_OPD_TOT": "Producers - Female - Acres Operated",
  "PRODS_FEM_NUM_OF_OPS_TOT": "Producers - Female - Number Of Operations",
  "PRODS_FEM_NUM_OF_PRODS_TOT": "Producers - Female - Number Of Producers",
  "PRODS_HIRED_MGR_NUM_PRODS_TOT": "Producers - Hired Manager - Number Of Producers",
  "PRODS_HSP_AC_OPD_TOT": "Producers - Hispanic - Acres Operated",
  "PRODS_HSP_NUM_OF_OPS_TOT": "Producers - Hispanic - Number Of Operations",
  "PRODS_HSP_NUM_OF_PRODS_TOT": "Producers - Hispanic - Number Of Producers",
  "PRODS_LND_USE_OR_CROP_DMKG_TOT": "Producers - Land Use Or Crop Decisionmaking - Number Of Producers",
  "PRODS_LVSK_DMKG_TOT": "Producers - Livestock Decisionmaking - Number Of Producers",
  "PRODS_MAL_AC_OPD_TOT": "Producers - Male - Acres Operated",
  "PRODS_MAL_NUM_OF_OPS_TOT": "Producers - Male - Number Of Operations",
  "PRODS_MAL_NUM_OF_PRODS_TOT": "Producers - Male - Number Of Producers",
  "PRODS_MKTG_DMKG_NUM_OF_PROD_TOT": "Producers - Marketing Decisionmaking - Number Of Producers",
  "PRODS_MIL_SVC_ACT_DTY_AC_OPRD": "Producers - Military Service - Active Duty Now Or In The Past - Acres Operated",
  "PRODS_MIL_SVC_ACT_DTY_NUM_OPS": "Producers - Military Service - Active Duty Now Or In The Past - Number Of Operations",
  "PRODS_MIL_SVC_ACT_DTY_NUM_PROD": "Producers - Military Service - Active Duty Now Or In The Past - Number Of Producers",
  "PRODS_MIL_SVC_NO_ACT_RES_N_PRO": "Producers - Military Service - Never Served Or Only On Active Duty For Training In Reserves Or National Guard - Number Of Producers",
  "PRODS_MUL_RACE_AC_OPD_TOT": "Producers - Multi-Race - Acres Operated",
  "PRODS_MUL_RACE_NUM_OF_OPS_TOT": "Producers - Multi-Race - Number Of Operations",
  "PRODS_MUL_RACE_NUM_OF_PRODS_TOT": "Producers - Multi-Race - Number Of Producers",
  "PRODS_NTV_HWN_AC_OPD_TOT": "Producers - Native Hawaiian - Acres Operated",
  "PRODS_NTV_HWN_NUM_OF_OPS_TOT": "Producers - Native Hawaiian - Number Of Operations",
  "PRODS_NTV_HWN_NUM_OF_PRODS_TOT": "Producers - Native Hawaiian - Number Of Producers",
  "PRODS_NTV_HWN_OR_PAC_ISL_AC_OPR": "Producers - Native Hawaiian Or Other Pacific Islander - Acres Operated",
  "PRODS_NTV_HWN_OR_PAC_ISL_NUM_O": "Producers - Native Hawaiian Or Other Pacific Islander - Number Of Operations",
  "PRODS_NTV_HWN_OR_PAC_ISL_NUM_P": "Producers - Native Hawaiian Or Other Pacific Islander - Number Of Producers",
  "PRODS_PAC_ISL_EX_NTV_HWN_AC_O": "Producers - Pacific Islander - (Excl Native Hawaiian) - Acres Operated",
  "PRODS_PAC_ISL_EX_NTV_HWN_N_OPS": "Producers - Pacific Islander - (Excl Native Hawaiian) - Number Of Operations",
  "PRODS_PAC_ISL_EX_NTV_HWN_N_PRO": "Producers - Pacific Islander - (Excl Native Hawaiian) - Number Of Producers",
  "PRODS_PRI_OCC_EX_FRM_N_PRO": "Producers - Primary Occupation - (Excl Farming) - Number Of Producers",
  "PRODS_PRI_OCC_FRM_NUM_PRODS": "Producers - Primary Occupation - Farming - Number Of Producers",
  "PRODS_RECKPG_FINMGT_DMKG_N_PRO": "Producers - Record Keeping Or Financial Mgmt Decisionmaking - Number Of Producers",
  "PRODS_RES_NOT_OPR_NUM_OF_PRODS": "Producers - Residence - Not On Operation - Number Of Producers",
  "PRODS_RES_ON_OPR_NUM_OF_PRODS": "Producers - Residence - On Operation - Number Of Producers",
  "PRODS_WHT_AC_OPD_TOT": "Producers - White - Acres Operated",
  "PRODS_WHT_NUM_OF_OPS_TOT": "Producers - White - Number Of Operations",
  "PRODS_WHT_NUM_OF_PRODS_TOT": "Producers - White - Number Of Producers",
  "PRODS_YRS_ON_OPR_6_10_NUM_PRO": "Producers - Years On Any Operation - 6 To 10 Years - Number Of Producers",
  "PRODS_YRS_ON_OPR_GE_11_NUM_PRO": "Producers - Years On Any Operation - Greater Than or Equal To 11 Years - Number Of Producers",
  "PRODS_YRS_ON_OPR_LT_11_AC_OPD": "Producers - Years On Any Operation - Less Than 11 Years - Acres Operated",
  "PRODS_YRS_ON_OPR_LT_11_NUM_OPS": "Producers - Years On Any Operation - Less Than 11 Years - Number Of Operations",
  "PRODS_YRS_ON_OPR_LT_11_NUM_PRO": "Producers - Years On Any Operation - Less Than 11 Years - Number Of Producers",
  "PRODS_YRS_ON_OPR_LT_6_NUM_PRO": "Producers - Years On Any Operation - Less Than 6 Years - Number Of Producers",
  "PRODS_YRS_ON_PST_OPR_3_4_N_PRO": "Producers - Years On Present Operation - 3 To 4 Years - Number Of Producers",
  "PRODS_YRS_ON_PST_OPR_5_9_N_PRO": "Producers - Years On Present Operation - 5 To 9 Years - Number Of Producers",
  "PRODS_YRS_ON_PST_OPR_GE10_N_PRO": "Producers - Years On Present Operation - Greater Than or Equal To 10 Years - Number Of Producers",
  "PRODS_YRS_ON_PST_OPR_LT3_N_PRO": "Producers - Years On Present Operation - Less Than 3 Years - Number Of Producers",
  "RICE_ACRES_HVSD_TOT": "Rice - Acres Harvested",
  "RICE_OPS_W_AREA_HVSD_1000_PLS": "Rice - Operations With Area Harvested - Area Harvested: (1,000 Or More Acres)",
  "RICE_OPS_W_AREA_HVSD_1_24_9": "Rice - Operations With Area Harvested - Area Harvested: (1.0 To 24.9 Acres)",
  "RICE_OPS_W_AREA_HVSD_100_249": "Rice - Operations With Area Harvested - Area Harvested: (100 To 249 Acres)",
  "RICE_OPS_W_AREA_HVSD_25_99_9": "Rice - Operations With Area Harvested - Area Harvested: (25.0 To 99.9 Acres)",
  "RICE_OPS_W_AREA_HVSD_250_499": "Rice - Operations With Area Harvested - Area Harvested: (250 To 499 Acres)",
  "RICE_OPS_W_AREA_HVSD_500_999": "Rice - Operations With Area Harvested - Area Harvested: (500 To 999 Acres)",
  "RICE_OPS_W_AREA_HVSD_TOT": "Rice - Operations With Area Harvested",
  "RICE_OPS_W_SALES_TOT": "Rice - Operations With Sales",
  "RICE_PROD_CWT_TOT": "Rice - Production, Measured In Hundredweight",
  "RICE_SALES_DOL_TOT": "Rice - Sales, Measured In US Dollars ($)",
  "RICE_IRRD_ACRES_HVSD_TOT": "Rice, Irrigated - Acres Harvested",
  "RICE_IRRD_OPS_W_AREA_HVSD_TOT": "Rice, Irrigated - Operations With Area Harvested",
  "SORGHUM_OPS_W_SALES_TOT": "Sorghum - Operations With Sales",
  "SORGHUM_SALES_DOL_TOT": "Sorghum - Sales, Measured In US Dollars ($)",
  "SORGHUM_GRN_ACRES_HVSD_TOT": "Sorghum, Grain - Acres Harvested",
  "SORGHUM_GRN_OPS_A_HVSD_1000_PLS": "Sorghum, Grain - Operations With Area Harvested - Area Harvested: (1,000 Or More Acres)",
  "SORGHUM_GRN_OPS_A_HVSD_1_24_9": "Sorghum, Grain - Operations With Area Harvested - Area Harvested: (1.0 To 24.9 Acres)",
  "SORGHUM_GRN_OPS_A_HVSD_100_249": "Sorghum, Grain - Operations With Area Harvested - Area Harvested: (100 To 249 Acres)",
  "SORGHUM_GRN_OPS_A_HVSD_25_99_9": "Sorghum, Grain - Operations With Area Harvested - Area Harvested: (25.0 To 99.9 Acres)",
  "SORGHUM_GRN_OPS_A_HVSD_250_499": "Sorghum, Grain - Operations With Area Harvested - Area Harvested: (250 To 499 Acres)",
  "SORGHUM_GRN_OPS_A_HVSD_500_999": "Sorghum, Grain - Operations With Area Harvested - Area Harvested: (500 To 999 Acres)",
  "SORGHUM_GRN_OPS_W_A_HVSD_TOT": "Sorghum, Grain - Operations With Area Harvested",
  "SORGHUM_GRN_PROD_BU_TOT": "Sorghum, Grain - Production, Measured In Bushels",
  "SORGHUM_GRN_IRRD_ACRES_HVSD_TOT": "Sorghum, Grain, Irrigated - Acres Harvested",
  "SORGHUM_GRN_IRRD_OPS_A_HVSD_TOT": "Sorghum, Grain, Irrigated - Operations With Area Harvested",
  "SORGHUM_IRR_SYP_ACRES_HVSD_TOT": "Sorghum, Irrigated, Syrup - Acres Harvested",
  "SORGHUM_IRR_SYP_OPS_A_HVSD_TOT": "Sorghum, Irrigated, Syrup - Operations With Area Harvested",
  "SORGHUM_SILAGE_ACRES_HVSD_TOT": "Sorghum, Silage - Acres Harvested",
  "SORGHUM_SILAGE_OPS_W_A_HVSD_TOT": "Sorghum, Silage - Operations With Area Harvested",
  "SORGHUM_SILAGE_PROD_TONS_TOT": "Sorghum, Silage - Production, Measured In Tons",
  "SORGHUM_SILAGE_IRR_ACR_HVSD_TOT": "Sorghum, Silage, Irrigated - Acres Harvested",
  "SORGHUM_SILAGE_IRR_OPS_HVSD_TOT": "Sorghum, Silage, Irrigated - Operations With Area Harvested",
  "SORGHUM_SYRUP_ACRES_HVSD_TOT": "Sorghum, Syrup - Acres Harvested",
  "SORGHUM_SYRUP_OPS_W_A_HVSD_TOT": "Sorghum, Syrup - Operations With Area Harvested",
  "SORGHUM_SYRUP_PROD_GAL_TOT": "Sorghum, Syrup - Production, Measured In Gallons",
  "SOYBEANS_ACRES_HVSD_TOT": "Soybeans - Acres Harvested",
  "SOYBEANS_OPS_W_A_HVSD_1000_PLS": "Soybeans - Operations With Area Harvested - Area Harvested: (1,000 Or More Acres)",
  "SOYBEANS_OPS_W_A_HVSD_1_24_9": "Soybeans - Operations With Area Harvested - Area Harvested: (1.0 To 24.9 Acres)",
  "SOYBEANS_OPS_W_A_HVSD_100_249": "Soybeans - Operations With Area Harvested - Area Harvested: (100 To 249 Acres)",
  "SOYBEANS_OPS_W_A_HVSD_25_99": "Soybeans - Operations With Area Harvested - Area Harvested: (25.0 To 99.9 Acres)",
  "SOYBEANS_OPS_W_A_HVSD_250_499": "Soybeans - Operations With Area Harvested - Area Harvested: (250 To 499 Acres)",
  "SOYBEANS_OPS_W_A_HVSD_500_999": "Soybeans - Operations With Area Harvested - Area Harvested: (500 To 999 Acres)",
  "SOYBEANS_OPS_W_A_HVSD_TOT": "Soybeans - Operations With Area Harvested",
  "SOYBEANS_OPS_WITH_SALES_TOT": "Soybeans - Operations With Sales",
  "SOYBEANS_PROD_BU_TOT": "Soybeans - Production, Measured In Bushels",
  "SOYBEANS_SALES_DOL_TOT": "Soybeans - Sales, Measured In US Dollars",
  "SOYBEANS_IRRD_ACRES_HVSD_TOT": "Soybeans, Irrigated - Acres Harvested",
  "SOYBEANS_IRRD_OPS_W_A_HVSD_TOT": "Soybeans, Irrigated - Operations With Area Harvested",
  "TRACTORS_INV": "Tractors - Inventory",
  "TRACTORS_OPS_WITH_INV": "Tractors - Operations With Inventory",
  "TRACTORS_40_99HP_INV": "Tractors, 40-99 PTO-HP - Inventory",
  "TRACTORS_40_99HP_OPS_W_INV": "Tractors, 40-99 PTO-HP - Operations With Inventory",
  "TRACTORS_40_99HP_GE5Y_INV": "Tractors, 40-99 PTO-HP, >= 5 Years Old - Inventory",
  "TRACTORS_40_99HP_GE5Y_OPS_W_INV": "Tractors, 40-99 PTO-HP, >= 5 Years Old - Operations With Inventory",
  "TRACTORS_40_99HP_LT5Y_INV": "Tractors, 40-99 PTO-HP, < 5 Years Old - Inventory",
  "TRACTORS_40_99HP_LT5Y_OPS_W_INV": "Tractors, 40-99 PTO-HP, < 5 Years Old - Operations With Inventory",
  "TRACTORS_GE100HP_INV": "Tractors, >= 100 PTO-HP - Inventory",
  "TRACTORS_GE100HP_OPS_W_INV": "Tractors, >= 100 PTO-HP - Operations With Inventory",
  "TRACTORS_GE100HP_GE5Y_INV": "Tractors, >= 100 PTO-HP, >= 5 Years Old - Inventory",
  "TRACTORS_GE100HP_GE5Y_OPS_W_INV": "Tractors, >= 100 PTO-HP, >= 5 Years Old - Operations With Inventory",
  "TRACTORS_GE100HP_LT5Y_INV": "Tractors, >= 100 PTO-HP, < 5 Years Old - Inventory",
  "TRACTORS_GE100HP_LT5Y_OPS_W_INV": "Tractors, >= 100 PTO-HP, < 5 Years Old - Operations With Inventory",
  "TRACTORS_GE5Y_INV_TOT": "Tractors, >= 5 Years Old - Inventory",
  "TRACTORS_GE5Y_OPS_W_INV": "Tractors, >= 5 Years Old - Operations With Inventory",
  "TRACTORS_LT40HP_INV": "Tractors, < 40 PTO-HP - Inventory",
  "TRACTORS_LT40HP_OPS_W_INV": "Tractors, < 40 PTO-HP - Operations With Inventory",
  "TRACTORS_LT40HP_GE5Y_INV": "TRACTORS_LT40HP_GE5Y_INV",
  "TRACTORS_LT40HP_GE5Y_OPS_W_INV": "TRACTORS_LT40HP_GE5Y_OPS_W_INV",
  "TRACTORS_LT40HP_LT5Y_INV": "Tractors, < 40 PTO-HP, < 5 Years Old - Inventory",
  "TRACTORS_LT40HP_LT5Y_OPS_W_INV": "Tractors, < 40 PTO-HP, < 5 Years Old - Operations With Inventory",
  "TRACTORS_LT5Y_INV": "Tractors, < 5 Years Old - Inventory",
  "TRACTORS_LT5Y_OPS_W_INV": "Tractors, < 5 Years Old - Operations With Inventory",
  "TRUCKS_INCL_P_UPS_INV_TOT": "Trucks, Incl Pickups - Inventory",
  "TRUCKS_INCL_P_UPS_OPS_W_INV": "Trucks, Incl Pickups - Operations With Inventory",
  "TRUCKS_INCL_P_UPS_GE5Y_INV": "Trucks, Incl Pickups, >= 5 Years Old - Inventory",
  "TRUCKS_INCL_P_UPS_GE5Y_OPS_INV": "Trucks, Incl Pickups, >= 5 Years Old - Operations With Inventory",
  "TRUCKS_INCL_P_UPS_LT5Y_INV": "Trucks, Incl Pickups, < 5 Years Old - Inventory",
  "TRUCKS_INCL_P_UPS_LT5Y_OPS_INV": "Trucks, Incl Pickups, < 5 Years Old - Operations With Inventory",
  "TURKEYS_INV_TOT": "Turkeys - Inventory",
  "TURKEYS_OPS_WITH_INV_TOT": "Turkeys - Operations With Inventory",
  "TURKEYS_OPS_WITH_SALES_TOT": "Turkeys - Operations With Sales",
  "TURKEYS_SALES_IN_H_TOT": "Turkeys - Sales, Measured In Head",
  "TURKEYS_PRODCON_OPS_W_PROD": "Turkeys, Production Contract - Operations With Production",
  "TURKEYS_PRODCON_PROD_IN_H": "Turkeys, Production Contract - Production, Measured In Head",
  "WHEAT_ACRES_HVSD_TOT": "Wheat - Acres Harvested",
  "WHEAT_OPS_W_A_HVSD_1000_PLS": "Wheat - Operations With Area Harvested - Area Harvested: (1,000 Or More Acres)",
  "WHEAT_OPS_W_A_HVSD_1_24_9": "Wheat - Operations With Area Harvested - Area Harvested: (1.0 To 24.9 Acres)",
  "WHEAT_OPS_W_A_HVSD_100_249": "Wheat - Operations With Area Harvested - Area Harvested: (100 To 249 Acres)",
  "WHEAT_OPS_W_A_HVSD_25_99_9": "Wheat - Operations With Area Harvested - Area Harvested: (25.0 To 99.9 Acres)",
  "WHEAT_OPS_W_A_HVSD_250_499": "Wheat - Operations With Area Harvested - Area Harvested: (250 To 499 Acres)",
  "WHEAT_OPS_W_A_HVSD_500_999": "Wheat - Operations With Area Harvested - Area Harvested: (500 To 999 Acres)",
  "WHEAT_OPS_W_A_HVSD_TOT": "Wheat - Operations With Area Harvested",
  "WHEAT_OPS_W_SALES_TOT": "Wheat - Operations With Sales",
  "WHEAT_PROD_BU_TOT": "Wheat - Production, Measured In Bushels (BU)",
  "WHEAT_SALES_DOL_TOT": "Wheat - Sales, Measured In US Dollars ($)",
  "WHEAT_IRRD_ACRES_HVSD_TOT": "Wheat, Irrigated - Acres Harvested",
  "WHEAT_IRRD_OPS_W_A_HVSD_TOT": "Wheat, Irrigated - Operations With Area Harvested",
  "WHEAT_SPR_EX_DUR_ACRES_HVSD_TOT": "Wheat, Spring, (Excl Durum) - Acres Harvested",
  "WHEAT_SPR_EX_DUR_OPS_W_A_HVSD": "Wheat, Spring, (Excl Durum) - Operations With Area Harvested",
  "WHEAT_SPR_EX_DUR_PROD_BU_TOT": "Wheat, Spring, (Excl Durum) - Production, Measured In Bu",
  "WHEAT_SPR_EX_DUR_IR_AC_HVSD_TOT": "Wheat, Spring, (Excl Durum), Irrigated - Acres Harvested",
  "WHEAT_SPR_EX_DUR_IR_OPS_A_HVSD": "Wheat, Spring, (Excl Durum), Irrigated - Operations With Area Harvested",
  "WHEAT_SPR_DUR_AC_HVSD_TOT": "Wheat, Spring, Durum - Acres Harvested",
  "WHEAT_SPR_DUR_OPS_W_A_HVSD_TOT": "Wheat, Spring, Durum - Operations With Area Harvested",
  "WHEAT_SPR_DUR_PROD_BU_TOT": "Wheat, Spring, Durum - Production, Measured In Bu",
  "WHEAT_SPR_DUR_IRRD_AC_HVSD_TOT": "Wheat, Spring, Durum, Irrigated - Acres Harvested",
  "WHEAT_SPR_DUR_IRRD_OPS_W_A_HVSD": "Wheat, Spring, Durum, Irrigated - Operations With Area Harvested",
  "WHEAT_WINTER_ACRES_HVSD_TOT": "Wheat, Winter - Acres Harvested",
  "WHEAT_WINTER_OPS_W_A_HVSD_TOT": "Wheat, Winter - Operations With Area Harvested",
  "WHEAT_WINTER_PROD_BU_TOT": "Wheat, Winter - Production, Measured In Bushels (BU)",
  "WHEAT_WINTER_IRR_ACRES_HVSD_TOT": "Wheat, Winter, Irrigated - Acres Harvested",
  "WHEAT_WINT_IRR_OPS_W_A_HVSD_TOT": "Wheat, Winter, Irrigated - Operations With Area Harvested",
}